POST http://localhost:8080/events
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQHRlc3QuY29tIiwiZXhwIjoxNzA4MzQ1MDQ4LCJ1c2VySWQiOjJ9.sHeZd3et5LoibeLyLQFBP4H_wJh-hciLToT_KmYAqU8

{
  "name": "event1",
  "description": "description1",
  "location": "location1",
  "datetime": "2020-01-01T00:00:00.000Z"
}

###
POST http://localhost:8080/events
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJleHAiOjE3MDgzNDUwNzMsInVzZXJJZCI6MX0.RpMJ4EZKdsyqlfOZOB0vgkGEFFtB63GwsvHUC4AOfR4

{
  "name": "event2",
  "description": "description2",
  "location": "location2",
  "datetime": "2020-01-01T00:00:00.000Z"
}
