POST http://localhost:8080/events
content-type: application/json

{
  "name": "event1",
  "description": "description1",
  "location": "location1",
  "datetime": "2020-01-01T00:00:00.000Z"
}

###
POST http://localhost:8080/events
content-type: application/json

{
  "name": "event2",
  "description": "description2",
  "location": "location2",
  "datetime": "2020-01-01T00:00:00.000Z"
}
