PUT http://localhost:8080/events/4
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJleHAiOjE3MDgzNDY2MDAsInVzZXJJZCI6MX0.fJPxHyVQ2lk5QrOWayvfYz25esukUH0_KrtWG5dWjaA

{
  "Name": "event2 update",
  "Description": "event2 description update",
  "Location": "event2 location update",
  "DateTime": "2021-01-01T00:00:00Z"
}