PUT http://localhost:8080/events/2
content-type: application/json

{
  "Name": "event2 update",
  "Description": "event2 description update",
  "Location": "event2 location update",
  "DateTime": "2021-01-01T00:00:00Z"
}